
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NeoDanger
 */
public class general extends javax.swing.JFrame {

    /**
     * Creates new form general
     */
    public general() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        txtX1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        labelB = new javax.swing.JLabel();
        labelB2 = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelA2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 660));
        setMinimumSize(new java.awt.Dimension(500, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        txtA.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtA.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtAInputMethodTextChanged(evt);
            }
        });
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        txtA.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAPropertyChange(evt);
            }
        });
        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAKeyPressed(evt);
            }
        });
        getContentPane().add(txtA);
        txtA.setBounds(230, 70, 70, 40);

        txtB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB);
        txtB.setBounds(230, 120, 70, 40);

        txtC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });
        getContentPane().add(txtC);
        txtC.setBounds(230, 170, 70, 40);

        btnCal.setBackground(new java.awt.Color(0, 0, 0));
        btnCal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCal.setForeground(new java.awt.Color(255, 255, 255));
        btnCal.setText("Calcular");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCal);
        btnCal.setBounds(190, 370, 140, 40);

        txtX1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(txtX1);
        txtX1.setBounds(250, 480, 140, 40);

        txtX2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(txtX2);
        txtX2.setBounds(250, 550, 140, 40);

        labelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelB.setText("b");
        getContentPane().add(labelB);
        labelB.setBounds(110, 244, 40, 50);

        labelB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelB2.setText("b");
        getContentPane().add(labelB2);
        labelB2.setBounds(230, 250, 40, 30);

        labelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelA.setText("a");
        getContentPane().add(labelA);
        labelA.setBounds(340, 250, 40, 30);

        labelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelC.setText("c");
        getContentPane().add(labelC);
        labelC.setBounds(400, 254, 50, 30);

        labelA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelA2.setText("a");
        getContentPane().add(labelA2);
        labelA2.setBounds(310, 310, 50, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\NeoDanger\\Desktop\\formul.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 490, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
     try{
          int a = Integer.parseInt(txtA.getText());
          int b = Integer.parseInt(txtB.getText());
          int c = Integer.parseInt(txtC.getText());
          
          double Determinante = Math.pow(b, 2)-(4*a*c);        
       if( Determinante > 0){
          double  x1 = ((b*(-1))+ Math.sqrt(Determinante))/(2*a);
          double  x2 = ((b*(-1))- Math.sqrt(Determinante))/(2*a);
          txtX1.setText(Double.toString(x1));
          txtX2.setText(Double.toString(x2));
          
          
       
       }else{
        JOptionPane.showMessageDialog(null, "Cálculo Incorrecto"); 
       }
          
          
         
     }
     catch(NumberFormatException e){
    JOptionPane.showMessageDialog(null, "Campos Vacios o Incompletos" + e); 
     
     }
    }//GEN-LAST:event_btnCalActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
labelA.setText(txtA.getText());
  labelA2.setText(txtA.getText());
   labelB.setText(txtB.getText());
    labelB2.setText(txtB.getText());
     labelC.setText(txtC.getText());   
    }//GEN-LAST:event_txtAActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
 labelA.setText(txtA.getText());
  labelA2.setText(txtA.getText());
   labelB.setText(txtB.getText());
    labelB2.setText(txtB.getText());
     labelC.setText(txtC.getText());
     // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
 labelA.setText(txtA.getText());
  labelA2.setText(txtA.getText());
   labelB.setText(txtB.getText());
    labelB2.setText(txtB.getText());
     labelC.setText(txtC.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtAKeyPressed

    private void txtAPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPropertyChange

    private void txtAInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtAInputMethodTextChanged
labelA.setText(txtA.getText());
  labelA2.setText(txtA.getText());
   labelB.setText(txtB.getText());
    labelB2.setText(txtB.getText());
     labelC.setText(txtC.getText());  
     // TODO add your handling code here:
    }//GEN-LAST:event_txtAInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new general().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelA2;
    private javax.swing.JLabel labelB;
    private javax.swing.JLabel labelB2;
    private javax.swing.JLabel labelC;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
}
